update config to last purepower version

diff --git a/configs/zsh/powerlevel10k-settings b/configs/zsh/powerlevel10k-settings
--- a/configs/zsh/powerlevel10k-settings
+++ b/configs/zsh/powerlevel10k-settings
@@ -2,82 +2,118 @@
 # If you copy this file, keep the link to the original and this sentence intact; you are encouraged
 # to change everything else.
 
-local vi_insert=$'\u276F'
-local vi_cmd=$'\u276E'
-local lock=$'\uF023'
-local root=$'\uF09C'
-local jobs=$'\uF013'
+PURE_POWER_MODE=fancy
+[[ $TERM == xterm* ]] || : ${PURE_POWER_MODE:=portable}
 
-typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
-dir_writable dir vcs)
+() {
+  emulate -L zsh && setopt no_unset pipe_fail
 
-typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
-status command_execution_time root_indicator background_jobs time)
+  # `$(_pp_c x y`) evaluates to `y` if the terminal supports >= 256 colors and to `x` otherwise.
+  zmodload zsh/terminfo
+  if (( terminfo[colors] >= 256 )); then
+    function _pp_c() { echo -E $2 }
+  else
+    function _pp_c() { echo -E $1 }
+    typeset -g POWERLEVEL9K_IGNORE_TERM_COLORS=true
+  fi
 
-local p="\${\${\${KEYMAP:-0}:#vicmd}:+${${vi_insert//\\/\\\\}//\}/\\\}}}"
-p+="\${\${\$((!\${#\${KEYMAP:-0}:#vicmd})):#0}:+${${vi_cmd//\\/\\\\}//\}/\\\}}}"
+  # `$(_pp_s x y`) evaluates to `x` in portable mode and to `y` in fancy mode.
+  if [[ ${PURE_POWER_MODE:-fancy} == fancy ]]; then
+    function _pp_s() { echo -E $2 }
+  else
+    if [[ $PURE_POWER_MODE != portable ]]; then
+      echo -En "purepower: invalid mode: ${(qq)PURE_POWER_MODE}; " >&2
+      echo -E  "valid options are 'fancy' and 'portable'; falling back to 'portable'" >&2
+    fi
+    function _pp_s() { echo -E $1 }
+  fi
 
-typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
-typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
-typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
-typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
-typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.%F{002}${p}%f.%F{009}${p}%f) "
+  typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
+      dir_writable dir vcs)
 
-typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
-typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
-typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_{LEFT,RIGHT}_SEGMENTS=
+  typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
+      status command_execution_time background_jobs custom_rprompt context)
 
-typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=none
-typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_VISUAL_IDENTIFIER_COLOR=003
-typeset -g POWERLEVEL9K_LOCK_ICON=$lock
+  local ins=$(_pp_s '>' '❯')
+  local cmd=$(_pp_s '<' '❮')
+  if (( ${PURE_POWER_USE_P10K_EXTENSIONS:-1} )); then
+    local p="\${\${\${KEYMAP:-0}:#vicmd}:+${${ins//\\/\\\\}//\}/\\\}}}"
+    p+="\${\${\$((!\${#\${KEYMAP:-0}:#vicmd})):#0}:+${${cmd//\\/\\\\}//\}/\\\}}}"
+  else
+    p=$ins
+  fi
+  local ok="%F{$(_pp_c 002 076)}${p}%f"
+  local err="%F{$(_pp_c 001 196)}${p}%f"
 
-typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT}_BACKGROUND=none
-typeset -g POWERLEVEL9K_DIR_{ETC,DEFAULT}_FOREGROUND=209
-typeset -g POWERLEVEL9K_DIR_{HOME,HOME_SUBFOLDER}_FOREGROUND=039
-typeset -g POWERLEVEL9K_{ETC,FOLDER,HOME,HOME_SUB}_ICON=
+  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
+  typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
+  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
+  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
+  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.$ok.$err) "
 
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
-typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=076
-typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=014
-typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=011
-typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=001
-typeset -g POWERLEVEL9K_VCS_LOADING_ACTIONFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_LOADING_FOREGROUND
-typeset -g POWERLEVEL9K_VCS_{GIT,GIT_GITHUB,GIT_BITBUCKET,GIT_GITLAB,BRANCH}_ICON=
-typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'\b|'
-typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
-typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\b?'
-typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\b!'
-typeset -g POWERLEVEL9K_VCS_STAGED_ICON=$'\b+'
-typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
-typeset -g POWERLEVEL9K_VCS_TAG_ICON=$'\b#'
+  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
+  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
+  typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_{LEFT,RIGHT}_SEGMENTS=
 
-typeset -g POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND=none
-typeset -g POWERLEVEL9K_ROOT_ICON=$root
+  typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=none
+  typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_VISUAL_IDENTIFIER_COLOR=003
+  typeset -g POWERLEVEL9K_LOCK_ICON='#'
 
-typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
-typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none
-typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=002
-typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON=$jobs
+  typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT}_BACKGROUND=none
+  typeset -g POWERLEVEL9K_DIR_{ETC,DEFAULT}_FOREGROUND=$(_pp_c 003 209)
+  typeset -g POWERLEVEL9K_DIR_{HOME,HOME_SUBFOLDER}_FOREGROUND=$(_pp_c 004 039)
+  typeset -g POWERLEVEL9K_{ETC,FOLDER,HOME,HOME_SUB}_ICON=
 
-typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
-typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
-typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
-typeset -g POWERLEVEL9K_EXECUTION_TIME_ICON=
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
+  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$(_pp_c 002 076)
+  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$(_pp_c 006 014)
+  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$(_pp_c 003 011)
+  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$(_pp_c 005 244)
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=001
+  typeset -g POWERLEVEL9K_VCS_LOADING_ACTIONFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_LOADING_FOREGROUND
+  typeset -g POWERLEVEL9K_VCS_{GIT,GIT_GITHUB,GIT_BITBUCKET,GIT_GITLAB,BRANCH}_ICON=
+  typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'%{\b|%}'
+  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
+  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON=$'%{\b?%}'
+  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON=$'%{\b!%}'
+  typeset -g POWERLEVEL9K_VCS_STAGED_ICON=$'%{\b+%}'
+  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$(_pp_s '<' '⇣')
+  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$(_pp_s '>' '⇡')
+  typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
+  typeset -g POWERLEVEL9K_VCS_TAG_ICON=$'%{\b#%}'
 
-typeset -g POWERLEVEL9K_TIME_BACKGROUND=none
-typeset -g POWERLEVEL9K_TIME_FOREGROUND=244
-typeset -g POWERLEVEL9K_TIME_ICON=
+  typeset -g POWERLEVEL9K_STATUS_OK=false
+  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
+  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$(_pp_c 001 009)
+  typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=
 
-typeset -g POWERLEVEL9K_STATUS_OK=false
-typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
-typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=009
-typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$(_pp_c 005 101)
+  typeset -g POWERLEVEL9K_EXECUTION_TIME_ICON=
+
+  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
+  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none
+  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=002
+  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON=$(_pp_s '%%' '⇶')
+
+  typeset -g POWERLEVEL9K_CUSTOM_RPROMPT=custom_rprompt
+  typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_BACKGROUND=none
+  typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_FOREGROUND=$(_pp_c 004 012)
+
+  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,ROOT,REMOTE_SUDO,REMOTE,SUDO}_BACKGROUND=none
+  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,REMOTE_SUDO,REMOTE,SUDO}_FOREGROUND=$(_pp_c 007 244)
+  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$(_pp_c 003 011)
+
+  function custom_rprompt() {}  # redefine this to show stuff in custom_rprompt segment
+
+  unfunction _pp_c _pp_s
+} "$@"
 
 # vim: set ft=zsh:
